apiVersion: v1
kind: Service
metadata:
  name: truvoice-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: truvoice
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP  # Using ClusterIP since we'll use an ingress for public access 